### PR TITLE
Bugfix/fix vanilla renderer for slotted dom

### LINKED ISSUE #76: Cannot re-render slotted light dom when using the vanilla renderer
See: https://codepen.io/eddyloewen/pen/QWBqdZw

### PR DESCRIPTION
**Pull request by eddyloewen**
Closes #76

### CODE REVIEW

File: src/renderer/vanilla/util/render.js [hunk 1]
```diff
@@ -49,18 +49,11 @@ const isTemplateElement = (element) => {
...
-	if (_cachedTemplateElements[tagName]) {
-		return true;
-	}
-
-	const elementClass = customElements.get(tagName);
-	const isTemplateElement = elementClass && elementClass._$templateElement$ === true;
-
-	if (isTemplateElement) {
-		_cachedTemplateElements[tagName] = elementClass;
+	if (element.shadowRoot) {
```
Comment (quarkus) [inline src/renderer/vanilla/util/render.js:52]: @eddyloewen skuld we add this test to the other early return above as another OR case ?

Comment (eddyloewen) [reply src/renderer/vanilla/util/render.js]: Yeah! Good point 👍

Comment (eddyloewen) [reply src/renderer/vanilla/util/render.js]: Hold on... there is something fishy here... I changed the code but made a mistake but tests are still green :(
I'll have to check again tomorrow...

Comment (eddyloewen) [reply src/renderer/vanilla/util/render.js]: Found a solution! I couldn't manage to write a failing test for the situation. But maybe it is not as important because the current vanilla renderer will be soon obsolete and for the new renderer this should not be a problem.

**Review by quarkus — APPROVED** [review]
