### PR TITLE
fix: using special characters in attribute static strings

### LINKED ISSUE #134: [RENDERER] "=" sign in attribute will cause generating parts errors
* "=" sign in attribute will cause generating parts errors. E.g. link="/api/${resource}?id=${item.id}"

_Originally posted by @eddyloewen in https://github.com/webtides/element-js/issues/123#issuecomment-2199784625_

Tasks:

- [ ] fix failing tests for attribute enclosed by "" || ''  (it.skip('can use double, single or no quotes for attributes')           
- [ ] support attributes that contain "=" chars (value serialization)

### PR DESCRIPTION
**Pull request by eddyloewen**
closes #134

### CODE REVIEW

File: examples/attributes/attributes-element.js [hunk 1]
```diff
@@ -11,10 +11,12 @@ class AttributesElement extends TemplateElement {
...
     template() {
         const templateResult = html`
-            <div foo="bar" class="before:block before:content-[&apos;Festivus&apos;]">no interpolation</div>
-            <div foo="${'bar'}">single attribute interpolation</div>
-            <div foo="${'bar'}" bar="${'baz'}">multiple attribute interpolations</div>
-            <div foo="${'bar'} baz ${'foo'}">multiple interpolations in single attribute</div>
+            <div foo1="bar" class="before:block before:content-['Festivus']">no interpolation</div>
+            <div foo2="${'bar'}">single attribute interpolation</div>
+            <div foo3="${'bar'}" bar="${'baz'}">multiple attribute interpolations</div>
+            <div foo4="${'bar'} baz ${'foo'} before:content-['Festivus']">
```
Comment (quarkus) [inline examples/attributes/attributes-element.js:17]: what about the unquoted case ?
https://arc.net/l/quote/neouemuc

do we still test this somewhere ?

Comment (quarkus) [reply examples/attributes/attributes-element.js:17]: And what exatly is this. 
baz ${'foo'}
Just having a single/static interpolation somewhere through ${'foo'} ?

I mean .. it's cool but isn't it the same as conditional attributes ?

Comment (eddyloewen) [reply examples/attributes/attributes-element.js:17]: This is just an example element for debugging things in the browser through the dev server. The unquoted case is tested somewhere else.
baz ${'foo'} is showing what it looks like when attributes have interpolations inside static parts of the attribute value.

**Review by quarkus — APPROVED** [review]
